  /{{ hierarchy }}.json:
    type: {
      crud_object: {
        "security": "secured",
        "label": {{ label_with_parent }},
        "object_example": !include examples/expected_response/{{ label }}.json,
        "empty_response_example": !include examples/expected_response/empty_response.json,
        "create_object_type": create_{{ label }},
        "create_object_example": !include examples/expected_payload_for_creating_object/create_{{ label }}.json,
        "invalid_dn_example": !include examples/expected_response/invalid_dn.json
      } 
    }